// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FinTechBank.DataAccess.Models
{
    public partial class Cliente
    {
        public long IdCliente { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string NumeroCuenta { get; set; }
        public decimal? Saldo { get; set; }
        public DateTime? FechaNacimiento { get; set; }
        public string Direccion { get; set; }
        public string Telefono { get; set; }
        public string CorreoElectronico { get; set; }
        public short? TipoCliente { get; set; }
        public string EstadoCivil { get; set; }
        public string NumeroIdentifiacion { get; set; }
        public string Profesion { get; set; }
        public string Genero { get; set; }
        public string Nacionalidad { get; set; }
        public DateTime FechaCreacion { get; set; }
        public bool IdEstado { get; set; }
    }
}